### ISSUE TITLE
allow upload to redshift in another account

### ISSUE THREAD

**Issue by ron819** [airflow-plugins/redshift_plugin#12]
I have csv files in S3 in one account but the RedShift is on another account.
Is it possible to allow the operator to support it?

* This case of multiple accounts usually happens when organization is build with more than one company so that each company has it's own amazon account.  (Cross platform) 
Example that this is needed:
https://www.pmg.com/blog/cross-account-redshift-unload-copy/

**Comment by benjamingregory** [comment]
@ron819 This operator would support that as long as the IAM role has permissions to both the S3 bucket and Redshift. Those permissions would happen on the AWS level; not within Airflow.

You can specify the appropriate IAM role here:
https://github.com/airflow-plugins/redshift_plugin/blob/master/operators/s3_to_redshift_operator.py#L221
