### ISSUE TITLE
Rebuild option somewhat deceptive

### ISSUE THREAD

**Issue by joshuathompson** [airflow-plugins/redshift_plugin#2]
I expected rebuild to totally rebuild the table with new datatypes but it's actually just a truncate statement.  Maybe the current `rebuild` should be renamed `truncate` and there should be a separate rebuild which drops and recreates?

**Comment by benjamingregory** [comment]
Closed with https://github.com/airflow-plugins/redshift_plugin/commit/b1a2de5be5e370eea457d94c942355ad96c9d951
