### ISSUE TITLE
Change parameter name in S3ToRedshiftOperator Docstring

### ISSUE THREAD

**Issue by szeevs** [airflow-plugins/redshift_plugin#4]
In the S3ToRedshiftOperator Docstring, the  parameter mysql_conn_id should be changed to redshift_conn_id

**Comment by benjamingregory** [comment]
Thanks for finding that @szeevs!

Closed with https://github.com/airflow-plugins/redshift_plugin/commit/b5952083ee9e9e9f20ceeb08b2d0542ff0fcbc41
